services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: console-quickstart-dynamodb
    ports:
      - "8002:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
