name: Integration Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: dotnet restore tests/DynamoDb.ExpressionMapping.IntegrationTests/
      - run: dotnet build tests/DynamoDb.ExpressionMapping.IntegrationTests/ --configuration Release --no-restore
      - name: Integration tests
        run: >
          dotnet test tests/DynamoDb.ExpressionMapping.IntegrationTests/ --configuration Release --no-build
